### ISSUE TITLE
Развитие продолжения Selfeco

### ISSUE THREAD

**Issue by tretdm** [monobogdan/selfeco#4]
Отсутствие поддержки Android 2.1 и отсутствие самодельных HTTP-прокси не заставило себя ждать.

Поэтому я решил продолжить разработку проекта самостоятельно, но принудительно использовав старую старую Android Studio. Конкретно, [версию 3.1.4](https://developer.android.com/studio/archive). Это особенно важно, поскольку проекты, созданные преимущественно в старых версиях Android Studio (там возможно указать версию Gradle до 2.3.2), имеют хоть какое-то право поддерживать версии Android ниже, чем 2.2.

Как вам такая идея?

**Comment by tretdm** [comment]
Ну и на всякий репозиторий скину: https://github.com/tinelix/selfeco-plus

**Comment by monobogdan** [comment]
Привет. Норм тема, все приложения я уже и сам бэкпортировал на 1.5 :) Со дня на день выйдет клиент Telegram под 1.5+.

Приложения сейчас рефакторятся, минивкшечка получит унифицированный интерфейс с клиентом телеги, ютубчик - кучу опций
